path: /Users/engel/Documents/cocoDoom/datatest
train: images/run1
val: images/run1

names:
  0 :  a
  1 :  b
  2 :  c
  3 :  d
  4 :  e
  5 :  f
  6 :  g
  7 :  h
  8 :  i
  9 :  j
  10 :  k
  11 :  l
  12 :  m
  13 :  nn
  14 :  o
  15 :  p
  16 :  q
  17 :  r
  18 :  s
  19 :  t
  20 :  u
  21 :  v
  22 :  w
  23 :  x
  24 :  yy
  25 :  z
  26 :  a
  27 :  b
  28 :  c
  29 :  d
  30 :  e
  31 :  f
  32 :  g
  33 :  h
  34 :  i
  35 :  j
  36 :  k
  37 :  l
  38 :  m
  39 :  np
  40 :  o
  41 :  p
  42 :  q
  43 :  r
  44 :  s
  45 :  t
  46 :  u
  47 :  v
  48 :  w
  49 :  x
  50 :  yp
  51 :  z
  52 :  aa
  53 :  ba
  54 :  ca
  55 :  da
  56 :  ea
  57 :  fa
  58 :  ga
  59 :  ha
  60 :  ia
  61 :  ja
  62 :  ka
  63 :  la
  64 :  ma
  65 :  na
  66 :  oa
  67 :  pa
  68 :  qa
  69 :  ra
  70 :  sa
  71 :  ta
  72 :  ua
  73 :  va
  74 :  wa
  75 :  xa
  76 :  ya
  77 :  za
  78 :  aa
  79 :  ba
  80 :  ca
  81 :  da
  82 :  ea
  83 :  fa
  84 :  ga
  85 :  ha
  86 :  ia
  87 :  ja
  88 :  ka
  89 :  la
  90 :  ma
  91 :  na
  92 :  oa
  93 :  pa

