names:
  0: a
  1: b
  2: c
  3: d
  4: e
  5: f
  6: g
  7: h
  8: i
  9: j
  10: k
  11: l
  12: m
  13: o
  14: p
  15: q
  16: r
  17: s
  18: t
  19: u
  20: v
  21: w
  22: x
  23: z
  24: A
  25: B
  26: C
  27: D
  28: E
  29: F
  30: G
  31: H
  32: I
  33: J
  34: K
  35: L
  36: M
  37: O
  38: P
  39: Q
  40: R
  41: S
  42: T
  43: U
  44: V
  45: W
  46: X
  47: Z
  48: aa
  49: ba
  50: ca
  51: da
  52: ea
  53: fa
  54: ga
  55: ha
  56: ia
  57: ja
  58: ka
  59: la
  60: ma
  61: oa
  62: pa
  63: qa
  64: ra
  65: sa
  66: ta
  67: ua
  68: va
  69: wa
  70: xa
  71: za
  72: Aa
  73: Ba
  74: Ca
  75: Da
  76: Ea
  77: Fa
  78: Ga
  79: Ha
  80: Ia
  81: Ja
  82: Ka
  83: La
  84: Ma
  85: Oa
  86: Pa
  87: Qa
  88: Ra
  89: Sa
  90: Ta
  91: Ua
  92: Va
  93: Wa
# path: /kaggle/input/cocodoom/data
# test: images/run3
# train: images/run1
# val: images/run2

path: /Users/engel/Documents/cocoDoom/datatest
train: images/run1
val: images/run1